server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shiro?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      min-evictable-idle-time-millis: 600000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      filters: stat,wall,slf4j


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
      update-strategy: not_empty
      insert-strategy: not_empty
      select-strategy: not_empty
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# \u81EA\u5B9A\u4E49\u914D\u7F6E
jwt:
  token:
    name: Authorization